services:
  db:
    image: postgres:16
    container_name: artcourses_db
    environment:
      POSTGRES_DB: artcourses
      POSTGRES_USER: art
      POSTGRES_PASSWORD: artpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: